/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Alexander.Silva
 * Created: 15/10/2017
 */
-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 19:37:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_ebooks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ebooks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ebooks` DEFAULT CHARACTER SET utf8 ;
USE `db_ebooks` ;

-- -----------------------------------------------------
-- Table `db_ebooks`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ebooks`.`livro` (
  `id` BIGINT(1) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `editora` VARCHAR(255) NOT NULL,
  `ano` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ebooks`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ebooks`.`usuario` (
  `id` BIGINT(1) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` CHAR(12) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


